# Generated by Django 5.0.2 on 2024-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('date_release', models.DateTimeField()),
                ('type_products', models.CharField(choices=[('ENDURO', 'enduro'), ('PITBIKE', 'pitbike')], max_length=200)),
            ],
        ),
    ]
